- id: export-pixi-requirements
  name: Export Pixi requirements
  entry: export-pixi-requirements
  language: python
  pass_filenames: false
  stages: [pre-commit, manual]
  files: ^pixi\.lock$
  args: ["--platform", "linux-64"]
  